let alternateFrames = [
    1,
    2,
    3,
    4,
    5,
    "$\\omega$",
    "$\\omega+1$",
    "$\\omega+2$",
    "$\\omega+3$",
    "$\\omega+4$",
    "$\\omega+5$",
    "$\\omega 2$",
    "$\\omega 3$",
    "$\\omega 4$",
    "$\\omega 5$",
    "$\\omega^2$",
    "$\\omega^3$",
    "$\\omega^4$",
    "$\\omega^5$",
    "$\\omega^\\omega$",
    "$\\omega^{\\omega^{\\omega}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega}}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\omega}}}}}$",
    "$\\varepsilon_0$",
    "$\\varepsilon_0+1$",
    "$\\varepsilon_0+2$",
    "$\\varepsilon_0+3$",
    "$\\varepsilon_0+4$",
    "$\\varepsilon_0+5$",
    "$\\varepsilon_0 2$",
    "$\\varepsilon_0 3$",
    "$\\varepsilon_0 4$",
    "$\\varepsilon_0 5$",
    "$\\omega^{\\varepsilon_0+1}$",
    "$\\omega^{\\varepsilon_0+1}+1$",
    "$\\omega^{\\varepsilon_0+1}2$",
    "$\\omega^{\\varepsilon_0+1}3$",
    "$\\omega^{\\varepsilon_0+2}$",
    "$\\omega^{\\varepsilon_0+3}$",
    "$\\omega^{\\varepsilon_0+4}$",
    "$\\omega^{\\varepsilon_0+5}$",
    "$\\omega^{\\varepsilon_0+5}$",
    "$\\omega^{\\varepsilon_0 2}$",
    "$\\omega^{\\varepsilon_0 3}$",
    "$\\omega^{\\varepsilon_0 4}$",
    "$\\omega^{\\varepsilon_0 5}$",
    "$\\omega^{\\omega^{\\varepsilon_0+1}}$",
    "$\\omega^{\\omega^{\\omega^{\\varepsilon_0+1}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\varepsilon_0+1}}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\varepsilon_0+1}}}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\varepsilon_0+1}}}}}}$",
    "$\\varepsilon_1$",
    "$\\varepsilon_1+1$",
    "$\\varepsilon_1+2$",
    "$\\varepsilon_1+3$",
    "$\\varepsilon_1+4$",
    "$\\varepsilon_1+5$",
    "$\\varepsilon_1+\\omega$",
    "$\\varepsilon_1+\\omega 2$",
    "$\\varepsilon_1+\\omega 3$",
    "$\\varepsilon_1+\\omega 4$",
    "$\\varepsilon_1+\\omega^{\\omega}$",
    "$\\varepsilon_1+\\omega^{\\omega^{\\omega}}$",
    "$\\varepsilon_1+\\varepsilon_0$",
    "$\\varepsilon_1+\\omega^{\\varepsilon_0}$",
    "$\\varepsilon_1+\\omega^{\\omega^{\\varepsilon_0}}$",
    "$\\varepsilon_1+\\omega^{\\omega^{\\omega^{\\varepsilon_0}}}$",
    "$\\varepsilon_1 2$",
    "$\\varepsilon_1 3$",
    "$\\varepsilon_1 4$",
    "$\\varepsilon_1 5$",
    "$\\omega^{\\varepsilon_1+1}$",
    "$\\omega^{\\varepsilon_1+2}$",
    "$\\omega^{\\varepsilon_1+3}$",
    "$\\omega^{\\varepsilon_1+4}$",
    "$\\omega^{\\varepsilon_1+5}$",
    "$\\omega^{\\varepsilon_1 2}$",
    "$\\omega^{\\varepsilon_1 3}$",
    "$\\omega^{\\varepsilon_1 4}$",
    "$\\omega^{\\varepsilon_1 5}$",
    "$\\omega^{\\omega^{\\varepsilon_1+1}}$",
    "$\\omega^{\\omega^{\\omega^{\\varepsilon_1+1}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\varepsilon_1+1}}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\varepsilon_1+1}}}}}$",
    "$\\varepsilon_2$",
    "$\\varepsilon_3$",
    "$\\varepsilon_4$",
    "$\\varepsilon_5$",
    "$\\varepsilon_6$",
    "$\\varepsilon_\\omega$",
    "$\\varepsilon_{\\omega+1}$",
    "$\\varepsilon_{\\omega+2}$",
    "$\\varepsilon_{\\omega+3}$",
    "$\\varepsilon_{\\omega+4}$",
    "$\\varepsilon_{\\omega 2}$",
    "$\\varepsilon_{\\omega 3}$",
    "$\\varepsilon_{\\omega 4}$",
    "$\\varepsilon_{\\omega^{\\omega^\\omega}}$",
    "$\\varepsilon_{\\varepsilon_0}$",
    "$\\varepsilon_{\\varepsilon_{\\varepsilon_{0}}}$",
    "$\\varepsilon_{\\varepsilon_{\\varepsilon_{\\varepsilon_{0}}}}$",
    "$\\varepsilon_{\\varepsilon_{\\varepsilon_{\\varepsilon_{\\varepsilon_{0}}}}}$",
    "$\\zeta_0$",
    "$\\varepsilon_{\\zeta_0}$",
    "$\\varepsilon_{\\varepsilon_{\\zeta_0}}$",
    "$\\varepsilon_{\\varepsilon_{\\varepsilon_{\\zeta_0}}}$",
    "$\\varepsilon_{\\varepsilon_{\\varepsilon_{\\varepsilon_{\\zeta_0} }}}$",
    "$\\zeta_1$",
    "$\\zeta_2$",
    "$\\zeta_3$",
    "$\\zeta_4$",
    "$\\zeta_5$",
    "$\\zeta_\\omega$",
    "$\\zeta_{\\omega^2}$",
    "$\\zeta_{\\omega^3}$",
    "$\\zeta_{\\omega^4}$",
    "$\\zeta_{\\omega^\\omega}$",
    "$\\zeta_{\\omega^{\\omega^\\omega}}$",
    "$\\zeta_{\\varepsilon_{0}}$",
    "$\\zeta_{\\varepsilon_{1}}$",
    "$\\zeta_{\\varepsilon_{2}}$",
    "$\\zeta_{\\varepsilon_{3}}$",
    "$\\zeta_{\\varepsilon_{4}}$",
    "$\\zeta_{\\varepsilon_{\\varepsilon_{0}}}$",
    "$\\zeta_{\\varepsilon_{\\varepsilon_{\\varepsilon_{0}}}}$",
    "$\\zeta_{\\zeta_{0}}$",
    "$\\zeta_{\\zeta_{\\zeta_{0}}}$",
    "$\\zeta_{\\zeta_{\\zeta_{\\zeta_{0}}}}$",
    "$\\varphi_{3}(0)$",
    "$\\varphi_{3}(1)$",
    "$\\varphi_{3}(2)$",
    "$\\varphi_{3}(3)$",
    "$\\varphi_{3}(4)$",
    "$\\varphi_{3}(5)$",
    "$\\varphi_{3}(\\omega)$",
    "$\\varphi_{3}(\\varepsilon_0)$",
    "$\\varphi_{3}(\\zeta_0)$",
    "$\\varphi_{3}(\\varphi_{3}(0))$",
    "$\\varphi_{3}(\\varphi_{3}(\\varphi_{3}(0)))$",
    "$\\varphi_{3}(\\varphi_{3}(\\varphi_{3}(\\varphi_{3}(0))))$",
    "$\\varphi_{4}(0)$",
    "$\\varphi_{4}(1)$",
    "$\\varphi_{4}(2)$",
    "$\\varphi_{4}(3)$",
    "$\\varphi_{4}(\\omega)$",
    "$\\varphi_{4}(\\varepsilon_{0})$",
    "$\\varphi_{4}(\\zeta_{0})$",
    "$\\varphi_{4}(\\varphi_{3}(0))$",
    "$\\varphi_{4}(\\varphi_{4}(0))$",
    "$\\varphi_{5}(0)$",
    "$\\varphi_{6}(0)$",
    "$\\varphi_{7}(0)$",
    "$\\varphi_{8}(0)$",
    "$\\varphi_{\\omega}(0)$",
    "$\\varphi_{\\varepsilon_{0 }}(0)$",
]