let alternateFrames = [
    1,
    2,
    3,
    4,
    5,
    "$\\omega$", //First transfinite ordinal
    "$\\omega+1$",
    "$\\omega+2$",
    "$\\omega+3$",
    "$\\omega+4$",
    "$\\omega+5$",
    "$\\omega 2$",
    "$\\omega 3$",
    "$\\omega 4$",
    "$\\omega 5$",
    "$\\omega^2$",
    "$\\omega^3$",
    "$\\omega^4$",
    "$\\omega^5$",
    "$\\omega^\\omega$",
    "$\\omega^{\\omega^{\\omega}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega}}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\omega}}}}}$",
    "$\\varepsilon_0$", //First limit ordinal
    "$\\varepsilon_0+1$",
    "$\\varepsilon_0+2$",
    "$\\varepsilon_0+3$",
    "$\\varepsilon_0+4$",
    "$\\varepsilon_0+5$",
    "$\\varepsilon_0 2$",
    "$\\varepsilon_0 3$",
    "$\\varepsilon_0 4$",
    "$\\varepsilon_0 5$",
    "$\\omega^{\\varepsilon_0+1}$",
    "$\\omega^{\\varepsilon_0+1}+1$",
    "$\\omega^{\\varepsilon_0+1}2$",
    "$\\omega^{\\varepsilon_0+1}3$",
    "$\\omega^{\\varepsilon_0+2}$",
    "$\\omega^{\\varepsilon_0+3}$",
    "$\\omega^{\\varepsilon_0+4}$",
    "$\\omega^{\\varepsilon_0+5}$",
    "$\\omega^{\\varepsilon_0+5}$",
    "$\\omega^{\\varepsilon_0 2}$",
    "$\\omega^{\\varepsilon_0 3}$",
    "$\\omega^{\\varepsilon_0 4}$",
    "$\\omega^{\\varepsilon_0 5}$",
    "$\\omega^{\\omega^{\\varepsilon_0+1}}$",
    "$\\omega^{\\omega^{\\omega^{\\varepsilon_0+1}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\varepsilon_0+1}}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\varepsilon_0+1}}}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\varepsilon_0+1}}}}}}$",
    "$\\varepsilon_1$", //Next epsilon number
    "$\\varepsilon_1+1$",
    "$\\varepsilon_1+2$",
    "$\\varepsilon_1+3$",
    "$\\varepsilon_1+4$",
    "$\\varepsilon_1+5$",
    "$\\varepsilon_1+\\omega$",
    "$\\varepsilon_1+\\omega 2$",
    "$\\varepsilon_1+\\omega 3$",
    "$\\varepsilon_1+\\omega 4$",
    "$\\varepsilon_1+\\omega^{\\omega}$",
    "$\\varepsilon_1+\\omega^{\\omega^{\\omega}}$",
    "$\\varepsilon_1+\\varepsilon_0$",
    "$\\varepsilon_1+\\omega^{\\varepsilon_0}$",
    "$\\varepsilon_1+\\omega^{\\omega^{\\varepsilon_0}}$",
    "$\\varepsilon_1+\\omega^{\\omega^{\\omega^{\\varepsilon_0}}}$",
    "$\\varepsilon_1 2$",
    "$\\varepsilon_1 3$",
    "$\\varepsilon_1 4$",
    "$\\varepsilon_1 5$",
    "$\\omega^{\\varepsilon_1+1}$",
    "$\\omega^{\\varepsilon_1+2}$",
    "$\\omega^{\\varepsilon_1+3}$",
    "$\\omega^{\\varepsilon_1+4}$",
    "$\\omega^{\\varepsilon_1+5}$",
    "$\\omega^{\\varepsilon_1 2}$",
    "$\\omega^{\\varepsilon_1 3}$",
    "$\\omega^{\\varepsilon_1 4}$",
    "$\\omega^{\\varepsilon_1 5}$",
    "$\\omega^{\\omega^{\\varepsilon_1+1}}$",
    "$\\omega^{\\omega^{\\omega^{\\varepsilon_1+1}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\varepsilon_1+1}}}}$",
    "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\varepsilon_1+1}}}}}$",
    "$\\varepsilon_2$",
    "$\\varepsilon_3$",
    "$\\varepsilon_4$",
    "$\\varepsilon_5$",
    "$\\varepsilon_6$",
    "$\\varepsilon_\\omega$",
    "$\\varepsilon_{\\omega+1}$",
    "$\\varepsilon_{\\omega+2}$",
    "$\\varepsilon_{\\omega+3}$",
    "$\\varepsilon_{\\omega+4}$",
    "$\\varepsilon_{\\omega 2}$",
    "$\\varepsilon_{\\omega 3}$",
    "$\\varepsilon_{\\omega 4}$",
    "$\\varepsilon_{\\omega^{\\omega^\\omega}}$",
    "$\\varepsilon_{\\varepsilon_0}$",
    "$\\varepsilon_{\\varepsilon_{\\varepsilon_{0}}}$",
    "$\\varepsilon_{\\varepsilon_{\\varepsilon_{\\varepsilon_{0}}}}$",
    "$\\varepsilon_{\\varepsilon_{\\varepsilon_{\\varepsilon_{\\varepsilon_{0}}}}}$",
    "$\\zeta_0$", //Next limit ordinal
    "$\\varepsilon_{\\zeta_0}$",
    "$\\varepsilon_{\\varepsilon_{\\zeta_0}}$",
    "$\\varepsilon_{\\varepsilon_{\\varepsilon_{\\zeta_0}}}$",
    "$\\varepsilon_{\\varepsilon_{\\varepsilon_{\\varepsilon_{\\zeta_0} }}}$",
    "$\\zeta_1$",
    "$\\zeta_2$",
    "$\\zeta_3$",
    "$\\zeta_4$",
    "$\\zeta_5$",
    "$\\zeta_\\omega$",
    "$\\zeta_{\\omega^2}$",
    "$\\zeta_{\\omega^3}$",
    "$\\zeta_{\\omega^4}$",
    "$\\zeta_{\\omega^\\omega}$",
    "$\\zeta_{\\omega^{\\omega^\\omega}}$",
    "$\\zeta_{\\varepsilon_{0}}$",
    "$\\zeta_{\\varepsilon_{1}}$",
    "$\\zeta_{\\varepsilon_{2}}$",
    "$\\zeta_{\\varepsilon_{3}}$",
    "$\\zeta_{\\varepsilon_{4}}$",
    "$\\zeta_{\\varepsilon_{\\varepsilon_{0}}}$",
    "$\\zeta_{\\varepsilon_{\\varepsilon_{\\varepsilon_{0}}}}$",
    "$\\zeta_{\\zeta_{0}}$",
    "$\\zeta_{\\zeta_{\\zeta_{0}}}$",
    "$\\zeta_{\\zeta_{\\zeta_{\\zeta_{0}}}}$",
    "$\\varphi_{3}(0)$", //Veblen function
    "$\\varphi_{3}(1)$",
    "$\\varphi_{3}(2)$",
    "$\\varphi_{3}(3)$",
    "$\\varphi_{3}(4)$",
    "$\\varphi_{3}(5)$",
    "$\\varphi_{3}(\\omega)$",
    "$\\varphi_{3}(\\varepsilon_0)$",
    "$\\varphi_{3}(\\zeta_0)$",
    "$\\varphi_{3}(\\varphi_{3}(0))$",
    "$\\varphi_{3}(\\varphi_{3}(\\varphi_{3}(0)))$",
    "$\\varphi_{3}(\\varphi_{3}(\\varphi_{3}(\\varphi_{3}(0))))$",
    "$\\varphi_{4}(0)$",
    "$\\varphi_{4}(1)$",
    "$\\varphi_{4}(2)$",
    "$\\varphi_{4}(3)$",
    "$\\varphi_{4}(\\omega)$",
    "$\\varphi_{4}(\\varepsilon_{0})$",
    "$\\varphi_{4}(\\zeta_{0})$",
    "$\\varphi_{4}(\\varphi_{3}(0))$",
    "$\\varphi_{4}(\\varphi_{4}(0))$",
    "$\\varphi_{5}(0)$",
    "$\\varphi_{6}(0)$",
    "$\\varphi_{7}(0)$",
    "$\\varphi_{8}(0)$",
    "$\\varphi_{\\omega}(0)$",
    "$\\varphi_{\\varepsilon_{0}}(0)$",
    "$\\varphi_{\\zeta_{0}}(0)$",
    "$\\varphi_{\\varphi_{3}(0)}(0)$",
    "$\\varphi_{\\varphi_{4}(0)}(0)$",
    "$\\varphi_{\\varphi_{5}(0)}(0)$",
    "$\\varphi_{\\varphi_{6}(0)}(0)$",
    "$\\varphi_{\\varphi_{\\varphi_{1}(0)}(0)}(0)$",
    "$\\varphi_{\\varphi_{\\varphi_{\\varphi_{1}(0)}(0)}(0)}(0)$",
    "$\\varphi_{\\varphi_{\\varphi_{\\varphi_{\\varphi_{1}(0)}(0)}(0)}(0)}(0)$",
    "$\\varphi_{\\varphi_{\\varphi_{\\varphi_{\\varphi_{\\varphi_{1}(0)}(0)}(0)}(0)}(0)}(0)$",
    "$\\varphi(1,0,0)$", //Extended Veblen function
    "$\\varphi(1,0,1)$",
    "$\\varphi(1,0,2)$",
    "$\\varphi(1,0,3)$",
    "$\\varphi(1,0,4)$",
    "$\\varphi(1,0,5)$",
    "$\\varphi(1,0,\\omega)$",
    "$\\varphi(1,0,\\varepsilon_{0})$",
    "$\\varphi(1,0,\\varphi_{2}(0))$",
    "$\\varphi(1,0,\\varphi_{3}(0))$",
    "$\\varphi(1,0,\\varphi_{4}(0))$",
    "$\\varphi(1,0,\\varphi_{5}(0))$",
    "$\\varphi(1,0,\\varphi_{\\omega}(0))$",
    "$\\varphi(1,0,\\varphi_{\\varepsilon_{0}}(0))$",
    "$\\varphi(1,0,\\varphi_{\\zeta_{0}}(0))$",
    "$\\varphi(1,0,\\varphi(1,0,0))$",
    "$\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,0)))$",
    "$\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,0))))$",
    "$\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,0)))))$",
    "$\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,0))))))$",
    "$\\varphi(1,1,0)$",
    "$\\varphi(1,1,1)$",
    "$\\varphi(1,1,2)$",
    "$\\varphi(1,1,3)$",
    "$\\varphi(1,1,4)$",
    "$\\varphi(1,1,5)$",
    "$\\varphi(1,1,\\omega)$",
    "$\\varphi(1,1,\\varepsilon_{0})$",
    "$\\varphi(1,1,\\zeta_{0})$",
    "$\\varphi(1,2,0)$",
    "$\\varphi(1,2,1)$",
    "$\\varphi(1,2,2)$",
    "$\\varphi(1,2,3)$",
    "$\\varphi(1,2,4)$",
    "$\\varphi(1,2,5)$",
    "$\\varphi(1,3,0)$",
    "$\\varphi(1,4,0)$",
    "$\\varphi(1,5,0)$",
    "$\\varphi(1,6,0)$",
    "$\\varphi(1,7,0)$",
    "$\\varphi(1,8,0)$",
    "$\\varphi(1,\\omega,0)$",
    "$\\varphi(1,\\varepsilon_{0},0)$",
    "$\\varphi(1,\\zeta_{0},0)$",
    "$\\varphi(1,\\varphi_{3}(0),0)$",
    "$\\varphi(1,\\varphi_{\\omega}(0),0)$",
    "$\\varphi(1,\\varphi_{\\varepsilon_{0}}(0),0)$",
    "$\\varphi(1,\\varphi_{\\zeta_{0}}(0),0)$",
    "$\\varphi(1,\\varphi(1,0,0),0)$",
    "$\\varphi(1,\\varphi(1,0,\\varphi(1,0,0)),0)$",
    "$\\varphi(1,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,0))),0)$",
    "$\\varphi(1,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,0)))),0)$",
    "$\\varphi(1,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,\\varphi(1,0,0))))),0)$",
    "$\\varphi(2,0,0)$",
    "$\\varphi(2,0,1)$",
    "$\\varphi(2,0,2)$",
    "$\\varphi(2,0,3)$",
    "$\\varphi(2,0,4)$",
    "$\\varphi(2,0,5)$",
    "$\\varphi(2,1,0)$",
    "$\\varphi(2,2,0)$",
    "$\\varphi(2,3,0)$",
    "$\\varphi(2,4,0)$",
    "$\\varphi(2,5,0)$",
    "$\\varphi(2,6,0)$",
    "$\\varphi(3,0,0)$",
    "$\\varphi(4,0,0)$",
    "$\\varphi(5,0,0)$",
    "$\\varphi(6,0,0)$",
    "$\\varphi(7,0,0)$",
    "$\\varphi(8,0,0)$",
    "$\\varphi(1,0,0,0)$",
    "$\\varphi(1,0,0,0,0)$",
    "$\\varphi(1,0,0,0,0,0)$",
    "$\\varphi(1,0,0,0,0,0,0)$",
    "$\\varphi(1,0,0,0,0,0,0,0)$",
    "$\\varphi(1,0,0,0,0,0,0,0,0)$",
    "$\\varphi(1,0,0,0,0,0,0,0,0,0)$",
    "$\\psi(\\Omega^{\\Omega^\\omega})$", //Ordinal Collapsing Function
    "$\\psi(\\Omega^{\\Omega^\\omega+1})$",
    "$\\psi(\\Omega^{\\Omega^\\omega+2})$",
    "$\\psi(\\Omega^{\\Omega^\\omega+3})$",
    "$\\psi(\\Omega^{\\Omega^\\omega 2})$",
    "$\\psi(\\Omega^{\\Omega^\\omega 3})$",
    "$\\psi(\\Omega^{\\Omega^\\omega 4})$",
    "$\\psi(\\Omega^{\\Omega^\\omega 5})$",
    "$\\psi(\\Omega^{\\Omega^\\Omega})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega+1}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega+2}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega+3}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega+4}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega+5}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega 2}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega 3}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega 4}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega 5}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega^{2}}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega^{3}}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega^{4}}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega^{5}}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega^{\\omega}}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega^{\\Omega}}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega^{\\Omega^{\\Omega}}}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega^{\\Omega^{\\Omega^{\\Omega}}}}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega^{\\Omega^{\\Omega^{\\Omega^{\\Omega}}}}}})$",
    "$\\psi(\\Omega^{\\Omega^{\\Omega^{\\Omega^{\\Omega^{\\Omega^{\\Omega^{\\Omega}}}}}}})$",
    "$\\psi(\\Omega_2)$", //Next uncountable ordinal
    "$\\psi(\\Omega_2+1)$",
    "$\\psi(\\Omega_2+2)$",
    "$\\psi(\\Omega_2+3)$",
    "$\\psi(\\Omega_2+4)$",
    "$\\psi(\\Omega_2+5)$",
    "$\\psi(\\Omega_2+\\omega)$",
    "$\\psi(\\Omega_2+\\Omega)$",
    "$\\psi(\\Omega_2 2)$",
    "$\\psi(\\Omega_2 3)$",
    "$\\psi(\\Omega_2 4)$",
    "$\\psi(\\Omega_2 5)$",
    "$\\psi(\\Omega_2 \\omega)$",
    "$\\psi(\\Omega_2 \\Omega)$",
    "$\\psi(\\Omega_2^2)$",
    "$\\psi(\\Omega_2^3)$",
    "$\\psi(\\Omega_2^4)$",
    "$\\psi(\\Omega_2^5)$",
    "$\\psi(\\Omega_2^{\\Omega_2})$",
    "$\\psi(\\Omega_2^{\\Omega_2^{\\Omega_2}})$",
    "$\\psi(\\Omega_2^{\\Omega_2^{\\Omega_2^{\\Omega_2}}})$",
    "$\\psi(\\Omega_2^{\\Omega_2^{\\Omega_2^{\\Omega_2^{\\Omega_2}}}})$",
    "$\\psi(\\Omega_2^{\\Omega_2^{\\Omega_2^{\\Omega_2^{\\Omega_2^{\\Omega_2}}}}})$",
    "$\\psi(\\Omega_2^{\\Omega_2^{\\Omega_2^{\\Omega_2^{\\Omega_2^{\\Omega_2^{\\Omega_2}}}}}})$",
    "$\\psi(\\Omega_3)$",
    "$\\psi(\\Omega_3^{\\Omega_3})$",
    "$\\psi(\\Omega_3^{\\Omega_3^{\\Omega_3}})$",
    "$\\psi(\\Omega_3^{\\Omega_3^{\\Omega_3^{\\Omega_3}}})$",
    "$\\psi(\\Omega_3^{\\Omega_3^{\\Omega_3^{\\Omega_3^{\\Omega_3}}}})$",
    "$\\psi(\\Omega_3^{\\Omega_3^{\\Omega_3^{\\Omega_3^{\\Omega_3^{\\Omega_3}}}}})$",
    "$\\psi(\\Omega_4)$",
    "$\\psi(\\Omega_5)$",
    "$\\psi(\\Omega_6)$",
    "$\\psi(\\Omega_7)$",
    "$\\psi(\\Omega_8)$",
    "$\\psi(\\Omega_9)$",
    "$\\psi(\\Omega_\\omega)$",
    "$\\psi(\\Omega_\\Omega)$",
    "$\\psi(\\Omega_{\\Omega_{\\omega}})$",
    "$\\psi(\\Omega_{\\Omega_{\\Omega}})$",
    "$\\psi(\\Omega_{\\Omega_{\\Omega_{\\Omega}}})$",
    "$\\psi(\\Omega_{\\Omega_{\\Omega_{\\Omega_{\\Omega}}}})$",
    "$\\psi(\\Omega_{\\Omega_{\\Omega_{\\Omega_{\\Omega_{\\Omega}}}}})$",
    "$\\psi(\\Omega_{\\Omega_{\\Omega_{\\Omega_{\\Omega_{\\Omega_{\\Omega}}}}}})$",
    "$\\psi(\\psi_I(0))$", //OCF with inaccessible cardinal
    "$\\psi(\\psi_I(0)+1)$",
    "$\\psi(\\psi_I(0)+2)$",
    "$\\psi(\\psi_I(0)+3)$",
    "$\\psi(\\psi_I(0)+4)$",
    "$\\psi(\\psi_I(0)+5)$",
    "$\\psi(\\psi_I(0)2)$",
    "$\\psi(\\psi_I(0)3)$",
    "$\\psi(\\psi_I(0)4)$",
    "$\\psi(\\psi_I(0)5)$",
    "$\\psi(\\psi_I(0)^{\\psi_I(0)})$",
    "$\\psi(\\psi_I(0)^{\\psi_I(0)^{\\psi_I(0)}})$",
    "$\\psi(\\psi_I(0)^{\\psi_I(0)^{\\psi_I(0)^{\\psi_I(0)}}})$",
    "$\\psi(\\psi_I(0)^{\\psi_I(0)^{\\psi_I(0)^{\\psi_I(0)^{\\psi_I(0)}}}})$",
    "$\\psi(\\psi_I(0)^{\\psi_I(0)^{\\psi_I(0)^{\\psi_I(0)^{\\psi_I(0)^{\\psi_I(0)}}}}})$",
    "$\\psi(\\psi_I(1))$",
    "$\\psi(\\psi_I(1)^{\\psi_I(1)})$",
    "$\\psi(\\psi_I(1)^{\\psi_I(1)^{\\psi_I(1)}})$",
    "$\\psi(\\psi_I(1)^{\\psi_I(1)^{\\psi_I(1)^{\\psi_I(1)}}})$",
    "$\\psi(\\psi_I(1)^{\\psi_I(1)^{\\psi_I(1)^{\\psi_I(1)^{\\psi_I(1)}}}})$",
    "$\\psi(\\psi_I(3))$",
    "$\\psi(\\psi_I(4))$",
    "$\\psi(\\psi_I(5))$",
    "$\\psi(\\psi_I(6))$",
    "$\\psi(\\psi_I(\\omega))$",
    "$\\psi(\\psi_I(\\Omega))$",
    "$\\psi(\\psi_I(\\psi_I(0)))$",
    "$\\psi(\\psi_I(\\psi_I(\\psi_I(0))))$",
    "$\\psi(\\psi_I(\\psi_I(\\psi_I(\\psi_I(0)))))$",
    "$\\psi(\\psi_I(\\psi_I(\\psi_I(\\psi_I(\\psi_I(0))))))$",
    "$\\psi(I)$",
    "$\\psi(I+1)$",
    "$\\psi(I+2)$",
    "$\\psi(I+3)$",
    "$\\psi(I+4)$",
    "$\\psi(I+5)$",
    "$\\psi(I+\\omega)$",
    "$\\psi(I+\\Omega)$",
    "$\\psi(I+\\Omega_2)$",
    "$\\psi(I+\\Omega_3)$",
    "$\\psi(I+\\Omega_4)$",
    "$\\psi(I+\\Omega_5)$",
    "$\\psi(I+\\Omega_\\omega)$",
    "$\\psi(I+\\Omega_\\Omega)$",
    "$\\psi(I+\\Omega_{\\Omega_\\Omega})$",
    "$\\psi(I+\\psi_I(0))$",
    "$\\psi(I+\\psi_I(1))$",
    "$\\psi(I+\\psi_I(2))$",
    "$\\psi(I+\\psi_I(3))$",
    "$\\psi(I+\\psi_I(4))$",
    "$\\psi(I+\\psi_I(5))$",
    "$\\psi(I+\\psi_I(\\omega))$",
    "$\\psi(I+\\psi_I(\\Omega))$",
    "$\\psi(I+\\psi_I(\\psi_I(0)))$",
    "$\\psi(I+\\psi_I(\\psi_I(\\psi_I(0))))$",
    "$\\psi(I+\\psi_I(\\psi_I(\\psi_I(\\psi_I(0)))))$",
    "$\\psi(I2)$",
    "$\\psi(I3)$",
    "$\\psi(I4)$",
    "$\\psi(I5)$",
    "$\\psi(I6)$",
    "$\\psi(I\\omega)$",
    "$\\psi(I\\Omega)$",
    "$\\psi(I\\psi_I(0))$",
    "$\\psi(I\\psi_I(\\psi_I(0)))$",
    "$\\psi(I\\psi_I(\\psi_I(\\psi_I(0))))$",
    "$\\psi(I^2)$",
    "$\\psi(I^3)$",
    "$\\psi(I^4)$",
    "$\\psi(I^5)$",
    "$\\psi(I^6)$",
    "$\\psi(I^\\omega)$",
    "$\\psi(I^\\Omega)$",
    "$\\psi(I^{\\psi_I(0)})$",
    "$\\psi(I^{\\psi_I(1)})$",
    "$\\psi(I^{\\psi_I(2)})$",
    "$\\psi(I^{\\psi_I(3)})$",
    "$\\psi(I^{\\psi_I(4)})$",
    "$\\psi(I^{\\psi_I(\\omega)})$",
    "$\\psi(I^{\\psi_I(\\Omega)})$",
    "$\\psi(I^{\\psi(I)})$",
    "$\\psi(I^I)$",
    "$\\psi(I^{I^2})$",
    "$\\psi(I^{I^3})$",
    "$\\psi(I^{I^4})$",
    "$\\psi(I^{I^5})$",
    "$\\psi(I^{I^I})$",
    "$\\psi(I^{I^{I^I}})$",
    "$\\psi(I^{I^{I^{I^{I}}}})$",
    "$\\psi(I^{I^{I^{I^{I^{I}}}}})$",
    "$\\psi(I^{I^{I^{I^{I^{I^{I}}}}}})$",
    "$\\psi(\\varepsilon_{I+1})$",
    "$\\psi(\\zeta_{I+1})$",
    "$\\psi(\\varphi_{3}(I+1))$",
    "$\\psi(\\varphi_{4}(I+1))$",
    "$\\psi(\\varphi_{\\omega}(I+1))$",
    "$\\psi(\\Omega_{I+1})$",
    "$\\psi(\\psi_{I_2}(0))$",
    "$\\psi(\\psi_{I_2}(1))$",
    "$\\psi(\\psi_{I_2}(2))$",
    "$\\psi(\\psi_{I_2}(3))$",
    "$\\psi(\\psi_{I_2}(4))$",
    "$\\psi(\\psi_{I_2}(5))$",
    "$\\psi(I_2)$", //Next inaccessible cardinal
    "$\\psi(I_2+1)$",
    "$\\psi(I_2+2)$",
    "$\\psi(I_2+3)$",
    "$\\psi(I_2+4)$",
    "$\\psi(I_2+5)$",
    "$\\psi(I_2 2)$",
    "$\\psi(I_2 3)$",
    "$\\psi(I_2 4)$",
    "$\\psi(I_2 5)$",
    "$\\psi(I_2^{I_2})$",
    "$\\psi(I_2^{I_2^{I_2}})$",
    "$\\psi(I_2^{I_2^{I_2^{I_2}}})$",
    "$\\psi(I_2^{I_2^{I_2^{I_2^{I_2}}}})$",
    "$\\psi(I_3)$",
    "$\\psi(I_4)$",
    "$\\psi(I_5)$",
    "$\\psi(I_6)$",
    "$\\psi(I_7)$",
    "$\\psi(I_{\\omega+1})$",
    "$\\psi(I_{\\omega+2})$",
    "$\\psi(I_{\\omega+3})$",
    "$\\psi(I_{\\omega+4})$",
    "$\\psi(I_{\\omega 2})$",
    "$\\psi(I_{\\omega 3})$",
    "$\\psi(I_{\\omega 4})$",
    "$\\psi(I_{\\omega 5})$",
    "$\\psi(I_{\\Omega})$",
    "$\\psi(I_{\\psi_I(0)})$",
    "$\\psi(I_{\\psi(I)})$",
    "$\\psi(I_{\\psi(I^2)})$",
    "$\\psi(I_{\\psi(I^3)})$",
    "$\\psi(I_{\\psi(I^4)})$",
    "$\\psi(I_{I})$",
    "$\\psi(I_{I_{I}})$",
    "$\\psi(I_{I_{I_{I}}})$",
    "$\\psi(I_{I_{I_{I_{I}}}})$",
    "$\\psi(I_{I_{I_{I_{I_{I}}}}})$",
    "$\\psi(\\psi_{I(1,0)}(0))$",
    "$\\psi(\\psi_{I(1,0)}(1))$",
    "$\\psi(\\psi_{I(1,0)}(2))$",
    "$\\psi(\\psi_{I(1,0)}(3))$",
    "$\\psi(\\psi_{I(1,0)}(4))$",
    "$\\psi(\\psi_{I(1,0)}(5))$",
    "$\\psi(I(1,0))$", //1-inaccessible
    "$\\psi(I(1,0)+1)$",
    "$\\psi(I(1,0)+2)$",
    "$\\psi(I(1,0)+3)$",
    "$\\psi(I(1,0)+4)$",
    "$\\psi(I(1,0)+5)$",
    "$\\psi(I(1,0)2)$",
    "$\\psi(I(1,0)3)$",
    "$\\psi(I(1,0)4)$",
    "$\\psi(I(1,0)5)$",
    "$\\psi(I(1,0)^2)$",
    "$\\psi(I(1,0)^2 2)$",
    "$\\psi(I(1,0)^2 3)$",
    "$\\psi(I(1,0)^2 4)$",
    "$\\psi(I(1,0)^2 5)$",
    "$\\psi(I(1,0)^3)$",
    "$\\psi(I(1,0)^4)$",
    "$\\psi(I(1,0)^5)$",
    "$\\psi(I(1,0)^6)$",
    "$\\psi(I(1,0)^I)$",
    "$\\psi(I(1,0)^{I_2})$",
    "$\\psi(I(1,0)^{I_3})$",
    "$\\psi(I(1,0)^{I_4})$",
    "$\\psi(I(1,0)^{I_5})$",
    "$\\psi(I(1,0)^{I_I})$",
    "$\\psi(I(1,0)^{I_{I_{I}}})$",
    "$\\psi(I(1,0)^{I_{I_{I_{I}}}})$",
    "$\\psi(I(1,0)^{\\psi_{I(1,0)}(0)})$",
    "$\\psi(I(1,0)^{\\psi_{I(1,0)}(1)})$",
    "$\\psi(I(1,0)^{\\psi_{I(1,0)}(2)})$",
    "$\\psi(I(1,0)^{\\psi_{I(1,0)}(3)})$",
    "$\\psi(I(1,0)^{\\psi_{I(1,0)}(4)})$",
    "$\\psi(I(1,0)^{\\psi_{I(1,0)}(5)})$",
    "$\\psi(I(1,0)^{I(1,0)})$",
    "$\\psi(I(1,0)^{I(1,0)^{I(1,0)}})$",
    "$\\psi(I(1,0)^{I(1,0)^{I(1,0)^{I(1,0)}}})$",
    "$\\psi(I(1,0)^{I(1,0)^{I(1,0)^{I(1,0)^{I(1,0)}}}})$",
    "$\\psi(I(1,1))$",
    "$\\psi(I(1,2))$",
    "$\\psi(I(1,3))$",
    "$\\psi(I(1,4))$",
    "$\\psi(I(1,5))$",
    "$\\psi(I(1,\\omega+1))$",
    "$\\psi(I(1,\\Omega))$",
    "$\\psi(I(1,\\psi_{I(1,0)}(0)))$",
    "$\\psi(I(1,\\psi(I(1,0))))$",
    "$\\psi(I(2,0))$",
    "$\\psi(I(2,1))$",
    "$\\psi(I(2,2))$",
    "$\\psi(I(2,3))$",
    "$\\psi(I(2,4))$",
    "$\\psi(I(2,5))$",
    "$\\psi(I(3,0))$",
    "$\\psi(I(4,0))$",
    "$\\psi(I(5,0))$",
    "$\\psi(I(6,0))$",
    "$\\psi(M^M)$", //OCF with Mahlo cardinal 
]
