let frames = [
  1,
  2,
  3,
  4,
  5,
  "$\\omega$",
  "$\\omega+1$",
  "$\\omega+2$",
  "$\\omega+3$",
  "$\\omega+4$",
  "$\\omega+5$",
  "$\\omega 2$",
  "$\\omega 2+1$",
  "$\\omega 2+2$",
  "$\\omega 2+3$",
  "$\\omega 2+4$",
  "$\\omega 2+5$",
  "$\\omega 3$",
  "$\\omega 4$",
  "$\\omega 5$",
  "$\\omega 6$",
  "$\\omega^2$",
  "$\\omega^2+1$",
  "$\\omega^2+2$",
  "$\\omega^2+3$",
  "$\\omega^2+4$",
  "$\\omega^2+5$",
  "$\\omega^2+\\omega$",
  "$\\omega^2+\\omega+1$",
  "$\\omega^2+\\omega+2$",
  "$\\omega^2+\\omega+3$",
  "$\\omega^2+\\omega+4$",
  "$\\omega^2+\\omega+5$",
  "$\\omega^2+\\omega 2$",
  "$\\omega^2+\\omega 2+1$",
  "$\\omega^2+\\omega 2+2$",
  "$\\omega^2+\\omega 2+3$",
  "$\\omega^2+\\omega 2+4$",
  "$\\omega^2+\\omega 2+5$",
  "$\\omega^2+\\omega 3$",
  "$\\omega^2+\\omega 4$",
  "$\\omega^2+\\omega 5$",
  "$\\omega^2+\\omega 6$",
  "$\\omega^2 2$",
  "$\\omega^2 2+1$",
  "$\\omega^2 2+2$",
  "$\\omega^2 2+3$",
  "$\\omega^2 2+4$",
  "$\\omega^2 2+5$",
  "$\\omega^2 2+\\omega$",
  "$\\omega^2 2+\\omega+1$",
  "$\\omega^2 2+\\omega+2$",
  "$\\omega^2 2+\\omega+3$",
  "$\\omega^2 2+\\omega+4$",
  "$\\omega^2 2+\\omega+5$",
  "$\\omega^2 2+\\omega 2$",
  "$\\omega^2 2+\\omega 3$",
  "$\\omega^2 2+\\omega 4$",
  "$\\omega^2 2+\\omega 5$",
  "$\\omega^2 2+\\omega 6$",
  "$\\omega^2 3$",
  "$\\omega^2 3+\\omega$",
  "$\\omega^2 3+\\omega 2$",
  "$\\omega^2 3+\\omega 3$",
  "$\\omega^2 3+\\omega 4$",
  "$\\omega^2 4$",
  "$\\omega^2 5$",
  "$\\omega^2 6$",
  "$\\omega^3$",
  "$\\omega^3+1$",
  "$\\omega^3+2$",
  "$\\omega^3+3$",
  "$\\omega^3+4$",
  "$\\omega^3+5$",
  "$\\omega^3+\\omega$",
  "$\\omega^3+\\omega 2$",
  "$\\omega^3+\\omega 3$",
  "$\\omega^3+\\omega 4$",
  "$\\omega^3+\\omega 5$",
  "$\\omega^3 2$",
  "$\\omega^3 3$",
  "$\\omega^3 4$",
  "$\\omega^3 5$",
  "$\\omega^3 6$",
  "$\\omega^4$",
  "$\\omega^5$",
  "$\\omega^6$",
  "$\\omega^7$",
  "$\\omega^\\omega$",
  "$\\omega^{\\omega}+1$",
  "$\\omega^{\\omega}+\\omega$",
  "$\\omega^{\\omega}+\\omega 2$",
  "$\\omega^{\\omega}+\\omega 3$",
  "$\\omega^{\\omega}+\\omega 4$",
  "$\\omega^{\\omega}+\\omega 5$",
  "$\\omega^{\\omega}2$",
  "$\\omega^{\\omega}3$",
  "$\\omega^{\\omega}4$",
  "$\\omega^{\\omega}5$",
  "$\\omega^{\\omega}6$",
  "$\\omega^{\\omega+1}$",
  "$\\omega^{\\omega+1}+\\omega$",
  "$\\omega^{\\omega+1}+\\omega 2$",
  "$\\omega^{\\omega+1}+\\omega 3$",
  "$\\omega^{\\omega+1}+\\omega 4$",
  "$\\omega^{\\omega+1}+\\omega 5$",
  "$\\omega^{\\omega+2}$",
  "$\\omega^{\\omega+3}$",
  "$\\omega^{\\omega+4}$",
  "$\\omega^{\\omega+5}$",
  "$\\omega^{\\omega 2}$",
  "$\\omega^{\\omega 2+1}$",
  "$\\omega^{\\omega 2+2}$",
  "$\\omega^{\\omega 2+3}$",
  "$\\omega^{\\omega 2+4}$",
  "$\\omega^{\\omega 2+5}$",
  "$\\omega^{\\omega 3}$",
  "$\\omega^{\\omega 4}$",
  "$\\omega^{\\omega 5}$",
  "$\\omega^{\\omega 6}$",
  "$\\omega^{\\omega^2}$",
  "$\\omega^{\\omega^2}+1$",
  "$\\omega^{\\omega^2}+2$",
  "$\\omega^{\\omega^2}+3$",
  "$\\omega^{\\omega^2}+4$",
  "$\\omega^{\\omega^2}+5$",
  "$\\omega^{\\omega^2}+\\omega$",
  "$\\omega^{\\omega^2}+\\omega+1$",
  "$\\omega^{\\omega^2}+\\omega+2$",
  "$\\omega^{\\omega^2}+\\omega+3$",
  "$\\omega^{\\omega^2}+\\omega+4$",
  "$\\omega^{\\omega^2}+\\omega+5$",
  "$\\omega^{\\omega^2}+\\omega 2$",
  "$\\omega^{\\omega^2}+\\omega 3$",
  "$\\omega^{\\omega^2}+\\omega 4$",
  "$\\omega^{\\omega^2}+\\omega 5$",
  "$\\omega^{\\omega^2}+\\omega 6$",
  "$\\omega^{\\omega^2}+\\omega^2+\\omega$",
  "$\\omega^{\\omega^2}+\\omega^2+\\omega 2$",
  "$\\omega^{\\omega^2}+\\omega^2+\\omega 3$",
  "$\\omega^{\\omega^2}+\\omega^2+\\omega 4$",
  "$\\omega^{\\omega^2}+\\omega^2+\\omega 5$",
  "$\\omega^{\\omega^2}+\\omega^2 2$",
  "$\\omega^{\\omega^2}+\\omega^2 3$",
  "$\\omega^{\\omega^2}+\\omega^2 4$",
  "$\\omega^{\\omega^2}+\\omega^2 5$",
  "$\\omega^{\\omega^2}+\\omega^2 6$",
  "$\\omega^{\\omega^2}+\\omega^3$",
  "$\\omega^{\\omega^2}+\\omega^4$",
  "$\\omega^{\\omega^2}+\\omega^5$",
  "$\\omega^{\\omega^2}+\\omega^6$",
  "$\\omega^{\\omega^2}+\\omega^7$",
  "$\\omega^{\\omega^2}+\\omega^\\omega$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+1$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+2$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+3$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+4$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+5$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+\\omega$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+\\omega 2$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+\\omega 3$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+\\omega 4$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+\\omega 5$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+\\omega^2$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+\\omega^3$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+\\omega^4$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+\\omega^5$",
  "$\\omega^{\\omega^2}+\\omega^\\omega+\\omega^6$",
  "$\\omega^{\\omega^2}+\\omega^\\omega 2$",
  "$\\omega^{\\omega^2}+\\omega^\\omega 3$",
  "$\\omega^{\\omega^2}+\\omega^\\omega 4$",
  "$\\omega^{\\omega^2}+\\omega^\\omega 5$",
  "$\\omega^{\\omega^2}2$",
  "$\\omega^{\\omega^2}2+\\omega$",
  "$\\omega^{\\omega^2}2+\\omega^\\omega$",
  "$\\omega^{\\omega^2}3$",
  "$\\omega^{\\omega^2}4$",
  "$\\omega^{\\omega^2}5$",
  "$\\omega^{\\omega^2}6$",
  "$\\omega^{\\omega^2}7$",
  "$\\omega^{\\omega^2+1}$",
  "$\\omega^{\\omega^2+2}$",
  "$\\omega^{\\omega^2+3}$",
  "$\\omega^{\\omega^2+4}$",
  "$\\omega^{\\omega^2+5}$",
  "$\\omega^{\\omega^2+6}$",
  "$\\omega^{\\omega^2 2}$",
  "$\\omega^{\\omega^2 3}$",
  "$\\omega^{\\omega^2 4}$",
  "$\\omega^{\\omega^2 5}$",
  "$\\omega^{\\omega^2 6}$",
  "$\\omega^{\\omega^3}$",
  "$\\omega^{\\omega^4}$",
  "$\\omega^{\\omega^5}$",
  "$\\omega^{\\omega^6}$",
  "$\\omega^{\\omega^7}$",
  "$\\omega^{\\omega^\\omega}$",
  "$\\omega^{\\omega^{\\omega^\\omega}}$",
  "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega}}}}$",
  "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\omega}}}}}$",
  "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\omega}}}}}}$",
  "$\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\omega^{\\omega}}}}}}}$",

  "$\\varepsilon_0$",
  "$\\varepsilon_0+1$",
  "$\\varepsilon_0+2$",
  "$\\varepsilon_0+3$",
  "$\\varepsilon_0+4$",
  "$\\varepsilon_0+5$",
  "$\\varepsilon_0+6$",
  "$\\varepsilon_0+\\omega$",
  "$\\varepsilon_0+\\omega+1$",
  "$\\varepsilon_0+\\omega+2$",
  "$\\varepsilon_0+\\omega+3$",
  "$\\varepsilon_0+\\omega+4$",
  "$\\varepsilon_0+\\omega+5$",
  "$\\varepsilon_0+\\omega 2$",
  "$\\varepsilon_0+\\omega 3$",
  "$\\varepsilon_0+\\omega 4$",
  "$\\varepsilon_0+\\omega 5$",
  "$\\varepsilon_0+\\omega 6$",
  "$\\varepsilon_0+\\omega^2$",
  "$\\varepsilon_0+\\omega^2+1$",
  "$\\varepsilon_0+\\omega^2+2$",
  "$\\varepsilon_0+\\omega^2+3$",
  "$\\varepsilon_0+\\omega^2 2$",
  "$\\varepsilon_0+\\omega^2 3$",
  "$\\varepsilon_0+\\omega^2 4$",
  "$\\varepsilon_0+\\omega^3$",
  "$\\varepsilon_0+\\omega^4$",
  "$\\varepsilon_0+\\omega^5$",
  "$\\varepsilon_0+\\omega^6$",
  "$\\varepsilon_0+\\omega^\\omega$",
  "$\\varepsilon_0+\\omega^{\\omega+1}$",
  "$\\varepsilon_0+\\omega^{\\omega+2}$",
  "$\\varepsilon_0+\\omega^{\\omega+3}$",
  "$\\varepsilon_0+\\omega^{\\omega+4}$",
  "$\\varepsilon_0+\\omega^{\\omega+5}$",
  "$\\varepsilon_0+\\omega^{\\omega 2}$",
  "$\\varepsilon_0+\\omega^{\\omega 3}$",
  "$\\varepsilon_0+\\omega^{\\omega 4}$",
  "$\\varepsilon_0+\\omega^{\\omega 5}$",
  "$\\varepsilon_0+\\omega^{\\omega 6}$",
  "$\\varepsilon_0+\\omega^{\\omega^{\\omega}}$",
  "$\\varepsilon_0+\\omega^{\\omega^{\\omega^{\\omega}}}$",
  "$\\varepsilon_0+\\omega^{\\omega^{\\omega^{\\omega^{\\omega}}}}$",
  "$\\varepsilon_0+\\omega^{\\omega^{\\omega^{\\omega^{\\omega^\\omega}}}}$",
  "$\\varepsilon_0 2$",
  "$\\varepsilon_0 2+1$",
  "$\\varepsilon_0 2+2$",
  "$\\varepsilon_0 2+3$",
  "$\\varepsilon_0 2+4$",
  "$\\varepsilon_0 2+5$",
  "$\\varepsilon_0 2+\\omega$",
  "$\\varepsilon_0 2+\\omega+1$",
  "$\\varepsilon_0 2+\\omega+2$",
  "$\\varepsilon_0 2+\\omega+3$",
  "$\\varepsilon_0 2+\\omega+4$",
  "$\\varepsilon_0 2+\\omega+5$",
  "$\\varepsilon_0 2+\\omega 2$",
  "$\\varepsilon_0 2+\\omega 2+1$",
  "$\\varepsilon_0 2+\\omega 2+2$",
  "$\\varepsilon_0 2+\\omega 2+3$",
  "$\\varepsilon_0 2+\\omega 2+4$",
  "$\\varepsilon_0 2+\\omega 2+5$",
  "$\\varepsilon_0 2+\\omega 3$",
  "$\\varepsilon_0 2+\\omega 4$",
  "$\\varepsilon_0 2+\\omega 5$",
  "$\\varepsilon_0 2+\\omega 6$",
  "$\\varepsilon_0 2+\\omega^{\\omega}$",
  "$\\varepsilon_0 2+\\omega^{\\omega}+1$",
  "$\\varepsilon_0 2+\\omega^{\\omega}+2$",
  "$\\varepsilon_0 2+\\omega^{\\omega}+3$",
  "$\\varepsilon_0 2+\\omega^{\\omega}+4$",
  "$\\varepsilon_0 2+\\omega^{\\omega}2$",
  "$\\varepsilon_0 2+\\omega^{\\omega}2+1$",
  "$\\varepsilon_0 2+\\omega^{\\omega}2+2$",
  "$\\varepsilon_0 2+\\omega^{\\omega}2+3$",
  "$\\varepsilon_0 2+\\omega^{\\omega}2+4$",
  "$\\varepsilon_0 2+\\omega^{\\omega}3$",
  "$\\varepsilon_0 2+\\omega^{\\omega}4$",
  "$\\varepsilon_0 2+\\omega^{\\omega}5$",
  "$\\varepsilon_0 2+\\omega^{\\omega}6$",
  "$\\varepsilon_0 2+\\omega^{\\omega}7$",
  "$\\varepsilon_0 2+\\omega^{\\omega+1}$",
  "$\\varepsilon_0 2+\\omega^{\\omega+1}+1$",
  "$\\varepsilon_0 2+\\omega^{\\omega+1}+2$",
  "$\\varepsilon_0 2+\\omega^{\\omega+1}+3$",
  "$\\varepsilon_0 2+\\omega^{\\omega+1}+4$",
  "$\\varepsilon_0 2+\\omega^{\\omega+1}2$",
  "$\\varepsilon_0 2+\\omega^{\\omega+1}3$",
  "$\\varepsilon_0 2+\\omega^{\\omega+1}4$",
  "$\\varepsilon_0 2+\\omega^{\\omega+1}5$",
  "$\\varepsilon_0 2+\\omega^{\\omega+2}$",
  "$\\varepsilon_0 2+\\omega^{\\omega+3}$",
  "$\\varepsilon_0 2+\\omega^{\\omega+4}$",
  "$\\varepsilon_0 2+\\omega^{\\omega+5}$",
  "$\\varepsilon_0 2+\\omega^{\\omega+6}$",
  "$\\varepsilon_0 2+\\omega^{\\omega 2}$",
  "$\\varepsilon_0 2+\\omega^{\\omega 2}+1$",
  "$\\varepsilon_0 2+\\omega^{\\omega 2}+2$",
  "$\\varepsilon_0 2+\\omega^{\\omega 2}+3$",
  "$\\varepsilon_0 2+\\omega^{\\omega 2}2$",
  "$\\varepsilon_0 2+\\omega^{\\omega 2}3$",
  "$\\varepsilon_0 2+\\omega^{\\omega 2}4$",
  "$\\varepsilon_0 2+\\omega^{\\omega 2+1}$",
  "$\\varepsilon_0 2+\\omega^{\\omega 2+2}$",
  "$\\varepsilon_0 2+\\omega^{\\omega 2+3}$",
  "$\\varepsilon_0 2+\\omega^{\\omega 2+4}$",
  "$\\varepsilon_0 2+\\omega^{\\omega 3}$",
  "$\\varepsilon_0 2+\\omega^{\\omega 4}$",
  "$\\varepsilon_0 2+\\omega^{\\omega 5}$",
  "$\\varepsilon_0 2+\\omega^{\\omega 6}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}}+1$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}}+2$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}}+3$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}}2$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}}3$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}}4$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}+1}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}+2}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}+3}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}+4}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}+5}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}2}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}3}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}4}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}5}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{2}6}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{3}}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{4}}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{5}}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{6}}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{\\omega}}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{\\omega^{\\omega}}}$",
  "$\\varepsilon_0 2+\\omega^{\\omega^{\\omega^{\\omega^{\\omega}}}}$",
  "$\\varepsilon_0 3$",
  "$\\varepsilon_0 4$",
  "$\\varepsilon_0 5$",
  "$\\varepsilon_0 6$",
  "$\\varepsilon_0 7$",
  "$\\varepsilon_0 8$",
  "$\\varepsilon_0 9$",
  "$\\varepsilon_0 10$",
  "$\\omega^{\\varepsilon_0+1}$",
];